spring:
  application:
    name: ApiGatewayService
  
  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/ifit-realm
          jwk-set-uri: http://localhost:9090/realms/ifit-realm/protocol/openid-connect/certs

  cloud:
    gateway:
      default-filters:
      routes:
        # Ruta pública para autenticación (sin TokenRelay)
        - id: IFIT-PUBLIC
          uri: lb://IFIT
          predicates:
            - Path=/ifit/api/v1/auth/**
          filters:
            - StripPrefix=3 
             
         # Ruta para servicios de AI (Ronnie y otros coaches)
        - id: RONNIE
          uri: lb://RONNIE
          predicates:
            - Path=/ifit/api/v1/ronnie/**, /ifit/api/v1/serena/**, /ifit/api/v1/kael/**, /ifit/api/v1/eliud/**, /ifit/api/v1/messages/**
          filters:
            - StripPrefix=3  
            - TokenRelay

        # Ruta privada para endpoints protegidos
        - id: IFIT-PRIVATE
          uri: lb://IFIT
          predicates:
            - Path=/ifit/api/v1/**
          filters:
            - StripPrefix=3  
            - TokenRelay     
         
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    # Spring Security
    org:
      springframework:
        security: 
          web: TRACE
          oauth2: TRACE
        # Spring Cloud Gateway
        cloud:
          gateway: TRACE
    
    # Reactor Netty (WebFlux)
    reactor:
      netty: TRACE
    
    # Eureka / Netflix Discovery
    com:
      netflix:
        eureka: DEBUG
        discovery: DEBUG