# Keycloak Config
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/ifit-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9090/realms/ifit-realm/protocol/openid-connect/certs

jwt.auth.converter.resource-id=springboot-ifit-client
jwt.auth.converter.principle-attribute=preferred_username

# Keycloak Logging
keycloak.client-id=springboot-ifit-client
keycloak.client-secret=JMDn1Tih39AflFF8xJE9P9YYLnIcPuIK
keycloak.token-url=http://localhost:9090/realms/ifit-realm/protocol/openid-connect/token

# Debug configuration
logging.level.org.keycloak = DEBUG
logging.level.org.springframework.security = DEBUG
logging.level.ifit.authentication_service.Keycloak = DEBUG


# Server Config
server.port=8083
server.servlet.context-path=/ifit/keycloak
spring.application.name=AUTHAPI

# --- EUREKA CLIENT CONFIGURATION ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
# IMPORTANTE: El nombre que Eureka usa para registrar el servicio
eureka.instance.instance-id=${spring.application.name}:${server.port}

